import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { mixSeed } from "@/src/world/seed";
import {
  ridgedChannelVarianceKept,
  ridgedFbm2D,
  ridgedFbmPair2D,
  valueNoise2D,
} from "@/src/world/noise";
import {
  MOUNTAIN_SHAPE,
  RIDGES_SOFT_OCTAVE_MEAN,
  RIDGES_SOFT_POW_MEAN,
  sampleNaturalTerrainHeight,
} from "@/src/world/terrain";

/**
 * `M-1` — the massif shape.
 *
 * The change this pins is a WORLD change: it moves collision, hydrology sources
 * and every frame with a mountain in it. So the first thing tested is where it
 * does NOT act. The fixture is the SHIPPED kernel's output (House-Keeping
 * bb078a7, generated by running the base tree, never by this one), at 420
 * points over three seeds and three filter widths.
 */
interface ShippedPoint {
  seedHash: number;
  x: number;
  z: number;
  filterWidth: number;
  height: number;
  mountainRegion: number;
}
const SHIPPED: ShippedPoint[] = JSON.parse(
  readFileSync(join(__dirname, "fixtures", "natural-height-shipped.json"), "utf8"),
);

describe("M-1 containment", () => {
  it("returns the shipped height BIT FOR BIT wherever either gate is shut", () => {
    const outside = SHIPPED.filter((point) =>
      point.mountainRegion <= MOUNTAIN_SHAPE.gateLow
      || point.height <= MOUNTAIN_SHAPE.heightGateLowMeters);
    // The fixture must actually exercise the claim: most of a world is outside.
    expect(outside.length).toBeGreaterThan(300);
    for (const point of outside) {
      expect(sampleNaturalTerrainHeight(point.seedHash, point.x, point.z, point.filterWidth))
        .toBe(point.height);
    }
  });

  it("does move tall mountain ground, so the fixture is not vacuous", () => {
    const inside = SHIPPED.filter((point) =>
      point.mountainRegion > 0.5 && point.height > 300);
    expect(inside.length).toBeGreaterThan(12);
    const moved = inside.filter((point) => Math.abs(
      sampleNaturalTerrainHeight(point.seedHash, point.x, point.z, point.filterWidth) - point.height,
    ) > 5);
    expect(moved.length).toBeGreaterThan(inside.length * 0.7);
  });

  it("keeps the height gate clear of every coastline and beach", () => {
    // Nothing at or below this height may ever move: the waterline, the shore
    // band the classifier and the vegetation both key on, and the lowest
    // airfields all live under it.
    expect(MOUNTAIN_SHAPE.heightGateLowMeters).toBeGreaterThanOrEqual(15);
    expect(MOUNTAIN_SHAPE.heightGateHighMeters).toBeGreaterThan(MOUNTAIN_SHAPE.heightGateLowMeters);
    expect(MOUNTAIN_SHAPE.gateLow).toBeGreaterThan(0);
  });
});

describe("M-1 the soft ridge channel", () => {
  it("leaves the hard half identical to ridgedFbm2D at every filter width", () => {
    const pair = { hard: 0, soft: 0 };
    for (let index = 0; index < 600; index += 1) {
      const x = ((index * 0.754_877_666_2) % 1) * 900 - 450;
      const z = ((index * 0.569_840_290_9) % 1) * 900 - 450;
      for (const filterWidth of [0, 8, 64, 512, 2_000]) {
        ridgedFbmPair2D(
          4242, x, z, 5, 2_550, filterWidth,
          MOUNTAIN_SHAPE.ridgeCusp, MOUNTAIN_SHAPE.ridgePersistence, RIDGES_SOFT_OCTAVE_MEAN, pair);
        expect(pair.hard).toBe(ridgedFbm2D(4242, x, z, 5, 2_550, filterWidth));
        expect(pair.soft).toBeGreaterThanOrEqual(0);
        expect(pair.soft).toBeLessThanOrEqual(1);
      }
    }
  });

  it("rests at the two means the band-limit fade blends toward", () => {
    // Measured, not derived (640k samples, scratch script measure-soft-means):
    // a composite that fades toward the wrong mean makes coarse pages a
    // different HEIGHT from fine ones, which is a visible LOD step on a massif.
    const cusp = MOUNTAIN_SHAPE.ridgeCusp;
    const pair = { hard: 0, soft: 0 };
    let octave = 0;
    let composite = 0;
    const count = 60_000;
    for (let index = 0; index < count; index += 1) {
      const x = ((index * 0.754_877_666_2) % 1) * 3_000 - 1_500;
      const z = ((index * 0.569_840_290_9) % 1) * 3_000 - 1_500;
      const value = valueNoise2D(mixSeed(977, 31), x, z);
      const rounded = Math.max(0, 1 - Math.sqrt(value * value + cusp * cusp)) / (1 - cusp);
      octave += rounded * rounded;
      ridgedFbmPair2D(977, x, z, 5, 0, 0, cusp, MOUNTAIN_SHAPE.ridgePersistence,
        RIDGES_SOFT_OCTAVE_MEAN, pair);
      composite += Math.pow(pair.soft, MOUNTAIN_SHAPE.ridgeExponent);
    }
    expect(octave / count).toBeCloseTo(RIDGES_SOFT_OCTAVE_MEAN, 1);
    expect(Math.abs(octave / count - RIDGES_SOFT_OCTAVE_MEAN)).toBeLessThan(0.012);
    expect(Math.abs(composite / count - RIDGES_SOFT_POW_MEAN)).toBeLessThan(0.012);
  });

  it("fades with its own gain, not the hard channel's", () => {
    const soft = ridgedChannelVarianceKept(5, 2_550, 600, MOUNTAIN_SHAPE.ridgePersistence);
    const hard = ridgedChannelVarianceKept(5, 2_550, 600);
    // A lower gain puts more of the variance in the coarse octaves, which
    // survive a wide filter: the soft channel keeps MORE at the same width.
    expect(soft).toBeGreaterThan(hard);
    expect(ridgedChannelVarianceKept(5, 2_550, 0, MOUNTAIN_SHAPE.ridgePersistence)).toBe(1);
  });
});

describe("M-1 what the change is for", () => {
  // Seed "terra1" (base-36), the inland massif whose shipped summit is 1,602 m
  // at (35545, 12650). Shipped, over this window: median slope 53.9 degrees
  // and 35% of the ground steeper than 60 degrees at a 30 m baseline.
  const seedHash = SHIPPED[0]!.seedHash;
  const slopes: number[] = [];
  let tallest = -Infinity;
  for (let z = 12_650 - 1_800; z <= 12_650 + 1_800; z += 90) {
    for (let x = 35_545 - 1_800; x <= 35_545 + 1_800; x += 90) {
      const here = sampleNaturalTerrainHeight(seedHash, x, z, 0);
      tallest = Math.max(tallest, here);
      if (here < 300) continue;
      const dx = (sampleNaturalTerrainHeight(seedHash, x + 15, z, 0)
        - sampleNaturalTerrainHeight(seedHash, x - 15, z, 0)) / 30;
      const dz = (sampleNaturalTerrainHeight(seedHash, x, z + 15, 0)
        - sampleNaturalTerrainHeight(seedHash, x, z - 15, 0)) / 30;
      slopes.push((Math.atan(Math.hypot(dx, dz)) * 180) / Math.PI);
    }
  }
  slopes.sort((first, second) => first - second);

  it("a massif is mostly walkable-to-scrambling ground with a few per cent of cliff", () => {
    expect(slopes.length).toBeGreaterThan(800);
    const median = slopes[Math.floor(slopes.length / 2)]!;
    const cliffShare = slopes.filter((slope) => slope > 60).length / slopes.length;
    // The CORE of a massif, which is its steepest 13 km2; the wider +-3 km
    // region measures 36-40 degrees. Shipped here: 53.9 degrees and 35% cliff.
    console.info(`M-1 massif core: median ${median.toFixed(1)} deg, cliff ${(cliffShare * 100).toFixed(1)}%`);
    expect(median).toBeLessThan(46);
    expect(median).toBeGreaterThan(22);
    expect(cliffShare).toBeLessThan(0.1);
  });

  it("and is still a tall mountain", () => {
    expect(tallest).toBeGreaterThan(1_300);
  });
});
